// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	adminRoleGroupFieldNames          = builder.RawFieldNames(&AdminRoleGroup{})
	adminRoleGroupRows                = strings.Join(adminRoleGroupFieldNames, ",")
	adminRoleGroupRowsExpectAutoSet   = strings.Join(stringx.Remove(adminRoleGroupFieldNames, "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	adminRoleGroupRowsWithPlaceHolder = strings.Join(stringx.Remove(adminRoleGroupFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"

	cacheAdminRoleGroupIdPrefix = "cache:adminRoleGroup:id:"
)

type (
	adminRoleGroupModel interface {
		Insert(ctx context.Context, data *AdminRoleGroup) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AdminRoleGroup, error)
		Update(ctx context.Context, data *AdminRoleGroup) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAdminRoleGroupModel struct {
		sqlc.CachedConn
		table string
	}

	AdminRoleGroup struct {
		Id       int64 `db:"id"`
		AdminId  int64 `db:"admin_id"`
		RoleId   int64 `db:"role_id"`
		Status   int64 `db:"status"`    // 状态 0=开启 1=关闭
		IsDelete int64 `db:"is_delete"` // 是否删 0=否 1=是
	}
)

func newAdminRoleGroupModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultAdminRoleGroupModel {
	return &defaultAdminRoleGroupModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`admin_role_group`",
	}
}

func (m *defaultAdminRoleGroupModel) Delete(ctx context.Context, id int64) error {
	adminRoleGroupIdKey := fmt.Sprintf("%s%v", cacheAdminRoleGroupIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, adminRoleGroupIdKey)
	return err
}

func (m *defaultAdminRoleGroupModel) FindOne(ctx context.Context, id int64) (*AdminRoleGroup, error) {
	adminRoleGroupIdKey := fmt.Sprintf("%s%v", cacheAdminRoleGroupIdPrefix, id)
	var resp AdminRoleGroup
	err := m.QueryRowCtx(ctx, &resp, adminRoleGroupIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", adminRoleGroupRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAdminRoleGroupModel) Insert(ctx context.Context, data *AdminRoleGroup) (sql.Result, error) {
	adminRoleGroupIdKey := fmt.Sprintf("%s%v", cacheAdminRoleGroupIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, adminRoleGroupRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.AdminId, data.RoleId, data.Status, data.IsDelete)
	}, adminRoleGroupIdKey)
	return ret, err
}

func (m *defaultAdminRoleGroupModel) Update(ctx context.Context, data *AdminRoleGroup) error {
	adminRoleGroupIdKey := fmt.Sprintf("%s%v", cacheAdminRoleGroupIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, adminRoleGroupRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.AdminId, data.RoleId, data.Status, data.IsDelete, data.Id)
	}, adminRoleGroupIdKey)
	return err
}

func (m *defaultAdminRoleGroupModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheAdminRoleGroupIdPrefix, primary)
}

func (m *defaultAdminRoleGroupModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", adminRoleGroupRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAdminRoleGroupModel) tableName() string {
	return m.table
}
