// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	UserName string `json:"username"`
	PassWord string `json:"password"`
}

type LoginReply struct {
	Id           uint   `json:"id"`
	Name         string `json:"name"`
	AccessToken  string `json:"accessToken"`
	AccessExpire uint64  `json:"accessExpire"`
	RefreshAfter uint64  `json:"refreshAfter"`
}

type AdminInfoReq struct {
	Id uint `json:"id"`
}

type AdminInfoReply struct {
	Id   uint   `json:"id"`
	Name string `json:"name"`
}
