// Code generated by goctl. DO NOT EDIT.
package handler

import (
    "net/http"

    "erik-agile/system/admin/api/internal/svc"
    "erik-agile/system/admin/api/internal/svc/gorm"
    "github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext, db *gorm.Gormdb) {
    server.AddRoutes(
        []rest.Route{
            {
                Method:  http.MethodPost,
                Path:    "/system/admin/login",
                Handler: loginHandler(serverCtx, db),
            },
        },
    )

    server.AddRoutes(
        rest.WithMiddlewares(
            []rest.Middleware{serverCtx.AdminMiddle},
            []rest.Route{
                {
                    Method:  http.MethodPost,
                    Path:    "/system/admin",
                    Handler: adminCreateHandler(serverCtx, db),
                },
                {
                    Method:  http.MethodDelete,
                    Path:    "/system/admin",
                    Handler: adminDeleteHandler(serverCtx, db),
                },
                {
                    Method:  http.MethodPut,
                    Path:    "/system/admin",
                    Handler: adminPutHandler(serverCtx, db),
                },
                {
                    Method:  http.MethodGet,
                    Path:    "/system/admin",
                    Handler: adminHandler(serverCtx, db),
                },
                {
                    Method:  http.MethodGet,
                    Path:    "/system/admin/info",
                    Handler: adminInfoHandler(serverCtx, db),
                },
                {
                    Method:  http.MethodPost,
                    Path:    "/system/permission",
                    Handler: permissionCreateHandler(serverCtx, db),
                },
                {
                    Method:  http.MethodDelete,
                    Path:    "/system/permission",
                    Handler: permissionDeleteHandler(serverCtx, db),
                },
                {
                    Method:  http.MethodPut,
                    Path:    "/system/permission",
                    Handler: permissionPutHandler(serverCtx, db),
                },
                {
                    Method:  http.MethodGet,
                    Path:    "/system/permission",
                    Handler: permissionHandler(serverCtx, db),
                },
                {
                    Method:  http.MethodPost,
                    Path:    "/system/role",
                    Handler: roleCreateHandler(serverCtx, db),
                },
                {
                    Method:  http.MethodDelete,
                    Path:    "/system/role",
                    Handler: roleDeleteHandler(serverCtx, db),
                },
                {
                    Method:  http.MethodPut,
                    Path:    "/system/role",
                    Handler: rolePutHandler(serverCtx, db),
                },
                {
                    Method:  http.MethodGet,
                    Path:    "/system/role",
                    Handler: roleHandler(serverCtx, db),
                },
            }...,
        ),
        rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
    )
}
