// Code generated by goctl. DO NOT EDIT!
// Source: admin.proto

package adminclient

import (
	"context"

	"go-zero-agile/system/admin/rpc/types/admin"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AdminResponse = admin.AdminResponse
	IdRequest     = admin.IdRequest

	Admin interface {
		GetAdmin(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*AdminResponse, error)
	}

	defaultAdmin struct {
		cli zrpc.Client
	}
)

func NewAdmin(cli zrpc.Client) Admin {
	return &defaultAdmin{
		cli: cli,
	}
}

func (m *defaultAdmin) GetAdmin(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*AdminResponse, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.GetAdmin(ctx, in, opts...)
}
